### ISSUE TITLE
Re-order repo

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/rml-io#25]
See RML Star

**Comment by dachafra** [comment]
To be a bit consistent with similar issues in the rest of repositories and maintain everything well documented:

New structure:
- [ ] folder `spec` with all the resources for the specification (the current content of the repo)*
- [ ] folder `ontology`, which I think is coming from #20 
- [ ] folder `shapes`, coming from #21 
- [ ] folder `test-cases`, from #24 

Other changes:
- [ ] *Remember that all specs need to be conformant with W3C: https://respec.org/docs/, an example could be https://kg-construct.github.io/rml-star/spec/docs/

**Comment by DylanVanAssche** [comment]
@dachafra The spec is already using the CG-DRAFT thing like on rml-star, anything else we need for the last point?
I will re-arrange everything once the #20 ontology PR is in as some small changes are needed to the specification as well to 100% match the ontology

**Comment by dachafra** [comment]
No other changes are required at this moment :-D 
I only update the issue to be consistent with the rest of the repos ;-)

**Comment by DylanVanAssche** [comment]
Remove node_modules
